// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TEG.SSO.LogDBContext;

namespace TEG.SSO.LogDBContext.Migrations
{
    [DbContext(typeof(LogContext))]
    partial class LogContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TEG.SSO.Entity.DBModel.ErrorLog", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("ErrorMsg")
                        .HasColumnType("text");

                    b.Property<string>("IP")
                        .HasMaxLength(128);

                    b.Property<string>("LastUpdateAccountName")
                        .HasMaxLength(64);

                    b.Property<DateTime>("ModifyTime");

                    b.Property<string>("Request")
                        .HasColumnType("text");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<string>("Token")
                        .HasMaxLength(256);

                    b.Property<string>("Url")
                        .HasMaxLength(1024);

                    b.HasKey("ID");

                    b.ToTable("ErrorLog");
                });

            modelBuilder.Entity("TEG.SSO.Entity.DBModel.OperationLog", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccessHost")
                        .HasMaxLength(64);

                    b.Property<string>("AccountName")
                        .HasMaxLength(64);

                    b.Property<string>("ActionCode")
                        .HasMaxLength(64);

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("Description")
                        .HasMaxLength(512);

                    b.Property<string>("LastUpdateAccountName")
                        .HasMaxLength(64);

                    b.Property<DateTime>("ModifyTime");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<string>("SystemCode")
                        .HasMaxLength(64);

                    b.Property<string>("URL")
                        .HasMaxLength(256);

                    b.Property<int>("UserID");

                    b.Property<string>("UserToken")
                        .HasMaxLength(256);

                    b.HasKey("ID");

                    b.ToTable("OperationLog");
                });
#pragma warning restore 612, 618
        }
    }
}
